/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-dim": "#d9d9df",
        "error": "#ba1a1a",
        "on-primary-fixed": "#001b3c",
        "background": "#f9f9ff",
        "on-tertiary-container": "#ee9162",
        "on-secondary-container": "#54647a",
        "on-secondary-fixed-variant": "#38485d",
        "inverse-primary": "#a8c8ff",
        "secondary": "#505f76",
        "on-primary": "#ffffff",
        "tertiary": "#481900",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-surface": "#1a1c20",
        "surface-container": "#ededf3",
        "surface-container-high": "#e8e8ed",
        "surface-container-low": "#f3f3f9",
        "tertiary-container": "#6a2a02",
        "outline": "#737781",
        "on-tertiary-fixed": "#341000",
        "on-secondary": "#ffffff",
        "surface-variant": "#e2e2e8",
        "tertiary-fixed": "#ffdbcb",
        "surface-container-highest": "#e2e2e8",
        "surface-tint": "#335f9c",
        "on-error-container": "#93000a",
        "surface": "#f9f9ff",
        "primary": "#002752",
        "secondary-fixed": "#d3e4fe",
        "on-background": "#1a1c20",
        "surface-bright": "#f9f9ff",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#d0e1fb",
        "secondary-fixed-dim": "#b7c8e1",
        "primary-fixed-dim": "#a8c8ff",
        "on-secondary-fixed": "#0b1c30",
        "on-surface-variant": "#434750",
        "inverse-surface": "#2f3035",
        "primary-fixed": "#d5e3ff",
        "on-primary-fixed-variant": "#134783",
        "outline-variant": "#c3c6d1",
        "tertiary-fixed-dim": "#ffb693",
        "inverse-on-surface": "#f0f0f6",
        "primary-container": "#003d79",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#80aaec",
        "on-tertiary-fixed-variant": "#76330a"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "sidebar-collapsed": "72px",
        "stack-gap": "16px",
        "unit": "4px",
        "sidebar-expanded": "260px",
        "container-max": "1440px",
        "gutter": "24px",
        "margin-page": "32px"
      },
      "fontFamily": {
        "h1": ["Inter"],
        "body-base": ["Inter"],
        "label-sm": ["Inter"],
        "h3": ["Inter"],
        "data-tabular": ["Inter"],
        "h2": ["Inter"],
        "label-md": ["Inter"],
        "body-sm": ["Inter"]
      },
      "fontSize": {
        "h1": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-base": ["16px", { "lineHeight": "24px", "letterSpacing": "0", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "h3": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "data-tabular": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "h2": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "body-sm": ["14px", { "lineHeight": "20px", "letterSpacing": "0", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
